
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';
import ReduxProvider from "@/feature/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Climber Fashion",
  description: "Generated by Orosia Team",
};

interface IRootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
  messages: any;
}

export default async function LocaleLayout({
  children,
  params: {locale}
}: IRootLayoutProps) {
 
  const messages = await getMessages();
 
  return (
    <html lang={locale}>
      <body>
      <ReduxProvider>
        <NextIntlClientProvider messages={messages}>
          <div>
          {children}
          </div>
        </NextIntlClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}